INSERT INTO genre (genre_name) VALUES ('biography');
INSERT INTO genre (genre_name) VALUES ('business');
INSERT INTO genre (genre_name) VALUES ('classics');
INSERT INTO genre (genre_name) VALUES ('crime');
INSERT INTO genre (genre_name) VALUES ('fantasy');
INSERT INTO genre (genre_name) VALUES ('fiction');
INSERT INTO genre (genre_name) VALUES ('lgbtq');
INSERT INTO genre (genre_name) VALUES ('historical fiction');
INSERT INTO genre (genre_name) VALUES ('history');
INSERT INTO genre (genre_name) VALUES ('horror');
INSERT INTO genre (genre_name) VALUES ('humor');
INSERT INTO genre (genre_name) VALUES ('memoir');
INSERT INTO genre (genre_name) VALUES ('music');
INSERT INTO genre (genre_name) VALUES ('mystery');
INSERT INTO genre (genre_name) VALUES ('nonfiction');
INSERT INTO genre (genre_name) VALUES ('paranormal');
INSERT INTO genre (genre_name) VALUES ('philosophy');
INSERT INTO genre (genre_name) VALUES ('poetry');
INSERT INTO genre (genre_name) VALUES ('psychology');
INSERT INTO genre (genre_name) VALUES ('religion');
INSERT INTO genre (genre_name) VALUES ('romance');
INSERT INTO genre (genre_name) VALUES ('science');
INSERT INTO genre (genre_name) VALUES ('science fiction');
INSERT INTO genre (genre_name) VALUES ('self help');
INSERT INTO genre (genre_name) VALUES ('suspense');
INSERT INTO genre (genre_name) VALUES ('spirtuality');
INSERT INTO genre (genre_name) VALUES ('sports');
INSERT INTO genre (genre_name) VALUES ('thriller');
INSERT INTO genre (genre_name) VALUES ('travel');
INSERT INTO genre (genre_name) VALUES ('ya');
INSERT INTO genre (genre_name) VALUES ('art');
INSERT INTO genre (genre_name) VALUES ('comics');
INSERT INTO genre (genre_name) VALUES ('contemporary');
INSERT INTO genre (genre_name) VALUES ('graphic novel');
